const mockData = [
  {
    id: 1,
    name: "Dr. Smith",
    role: "doctor",
    department: "Cardiology",
    contact: "9876543210",
    available: true,
    photo: "/images/reception.jpg",
    email: "smith@hospital.com",
    experience: 12,
    qualifications: "MBBS, MD",
    shift: "9 AM - 5 PM",
    appointments: {
      "2025-04-26": [
        { patient: "Dhiraj Choudhary", time: "07:50 AM" }
      ]
    }
  },
  {
    id: 2,
    name: "Dr. Johnson",
    role: "doctor",
    department: "Cardiology",
    contact: "9123456789",
    available: true,
    photo: "/images/hospital-bg.jpg",
    email: "johnson@hospital.com",
    experience: 10,
    qualifications: "MBBS, MD",
    shift: "9 AM - 5 PM",
  },
  {
    id: 3,
    name: "Dr. Williams",
    role: "doctor",
    department: "Neurology",
    contact: "9988776655",
    available: true,
    photo: "/images/reception.jpg",
    email: "williams@hospital.com",
    experience: 15,
    qualifications: "MBBS, DM Neurology",
    shift: "10 AM - 6 PM",
    appointments: {
      "2025-04-26": [
        { patient: "Swami Shardul", time: "09:00 AM" }
      ]
    }
  },
  {
    id: 4,
    name: "Dr. Brown",
    role: "doctor",
    department: "Neurology",
    contact: "9012345678",
    available: true,
    photo: "/images/hospital-bg.jpg",
    email: "brown@hospital.com",
    experience: 8,
    qualifications: "MBBS, MD",
    shift: "10 AM - 6 PM",
  },
  {
    id: 5,
    name: "Dr. Davis",
    role: "doctor",
    department: "Pediatrics",
    contact: "9345678901",
    available: true,
    photo: "/images/reception.jpg",
    email: "davis@hospital.com",
    experience: 9,
    qualifications: "MBBS, MD Pediatrics",
    shift: "9 AM - 5 PM",
  },
  {
    id: 6,
    name: "Dr. Miller",
    role: "doctor",
    department: "Orthopedics",
    contact: "9786543210",
    available: false,
    photo: "/images/window.svg",
    email: "miller@hospital.com",
    experience: 11,
    qualifications: "MBBS, MS Ortho",
    shift: "11 AM - 7 PM",
  },
  {
    id: 7,
    name: "Dr. Wilson",
    role: "doctor",
    department: "Dermatology",
    contact: "9456123789",
    available: true,
    photo: "/images/globe.svg",
    email: "wilson@hospital.com",
    experience: 7,
    qualifications: "MBBS, MD Dermatology",
    shift: "10 AM - 6 PM",
  },
  {
    id: 8,
    name: "Dr. Moore",
    role: "doctor",
    department: "Ophthalmology",
    contact: "9234567890",
    available: true,
    photo: "/images/next.svg",
    email: "moore@hospital.com",
    experience: 13,
    qualifications: "MBBS, MS Ophthalmology",
    shift: "9 AM - 5 PM",
  },

  // Nurses
  {
    id: 9,
    name: "Nurse Kavita",
    role: "nurse",
    department: "Pediatrics",
    contact: "9123456789",
    available: true,
    photo: "/images/hospital-bg.jpg",
    email: "kavita@hospital.com",
    experience: 6,
    qualifications: "BSc Nursing",
    shift: "Morning",
  },
  {
    id: 10,
    name: "Nurse Rohit Singh",
    role: "nurse",
    department: "ICU",
    contact: "9456123789",
    available: true,
    photo: "/images/globe.svg",
    email: "rohit.singh@hospital.com",
    experience: 7,
    qualifications: "GNM Nursing",
    shift: "Night",
  },
  {
    id: 11,
    name: "Nurse Aditi Joshi",
    role: "nurse",
    department: "Maternity",
    contact: "9234567890",
    available: false,
    photo: "/images/next.svg",
    email: "aditi.joshi@hospital.com",
    experience: 5,
    qualifications: "BSc Nursing",
    shift: "Evening",
  },

  // Ambulance Staff
  {
    id: 12,
    name: "Ravi Kumar",
    role: "ambulance",
    department: "Emergency",
    contact: "9988776655",
    available: true,
    photo: "/images/reception.jpg",
    email: "ravi@hospital.com",
    experience: 4,
    qualifications: "EMT Certified",
    shift: "24/7",
  },
  {
    id: 13,
    name: "Suresh Patil",
    role: "ambulance",
    department: "Emergency",
    contact: "9765432109",
    available: true,
    photo: "/images/vercel.svg",
    email: "suresh.patil@hospital.com",
    experience: 6,
    qualifications: "Paramedic",
    shift: "24/7",
  },
  {
    id: 14,
    name: "Anita Deshmukh",
    role: "ambulance",
    department: "Emergency",
    contact: "9341256780",
    available: false,
    photo: "/images/file.svg",
    email: "anita.deshmukh@hospital.com",
    experience: 3,
    qualifications: "EMT Certified",
    shift: "Day",
  },
];

export default mockData;
